title: "Ousmane Gueye - Portfolio PAD 2025"
description: "Designer Graphique & Développeur Full Stack - Hack'arthon PAD 2025"
email: ousmaneg186@gmail.com

# Thème GitHub Pages
theme: minima

# Plugins automatiques
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Informations personnelles
author:
  name: "Ousmane Gueye"
  email: "ousmaneg186@gmail.com"

# Langue
lang: fr

# Exclusions
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock